#ifndef __OSG4WEB_COREBASE_DEFINES__
#define	__OSG4WEB_COREBASE_DEFINES__ 1


#define		OSG4WEB_COREBASE_LIBNAME		"osg4web : corebase"
#define		OSG4WEB_COREBASE_VERSION 		"1.0.0.0"
#define		OSG4WEB_COREBASE_NAME			"CoreBase"

#endif //__OSG4WEB_COREBASE_DEFINES__