#ifndef __OSG4WEB_LOADEROPENGL_DEFINES__
#define	__OSG4WEB_LOADEROPENGL_DEFINES__ 1


#define		OSG4WEB_LOADEROPENGL_LIBNAME			"osg4web : Loader OpenGL"
#define		OSG4WEB_LOADEROPENGL_VERSION			"1.0.0.0"
#define		OSG4WEB_LOADEROPENGL_NAME				"LoaderOpenGL"


#endif //__OSG4WEB_LOADEROPENGL_DEFINES__
