#ifndef __OSG4WEB_COREOPENGL_DEFINES__
#define	__OSG4WEB_COREOPENGL_DEFINES__ 1


#define		OSG4WEB_COREOPENGL_LIBNAME		"osg4web : coreopengl"
#define		OSG4WEB_COREOPENGL_VERSION 		"1.0.0.0"
#define		OSG4WEB_COREOPENGL_NAME			"CoreOpenGL"

#endif //__OSG4WEB_COREOPENGL_DEFINES__