#ifndef __OSG4WEB_CORESCENEMODIFIER_DEFINES__
#define	__OSG4WEB_CORESCENEMODIFIER_DEFINES__ 1


#define		OSG4WEB_CORESCENEMODIFIER_LIBNAME		"osg4web : CoreSceneModifier"
#define		OSG4WEB_CORESCENEMODIFIER_VERSION 		"1.0.0.0"
#define		OSG4WEB_CORESCENEMODIFIER_NAME			"CoreSceneModifier"

#endif //__OSG4WEB_CORESCENEMODIFIER_DEFINES__

// here place additional defines