#ifndef __OSG4WEB_IEOSG4WEB_DEFINES__
#define __OSG4WEB_IEOSG4WEB_DEFINES__ 1

#define		OSG4WEB_SHELL_NAME		"ieOSG4Web"

#define		APPEND_TEMP_DIRECTORY	"\\osg4web"
#define		APPEND_CORES_DIRECTORY	"\\osg4web"

//#define		RENDER_WITH_TIMER_EVENT	1
#define		RENDER_DELAY				10
#define		EXIT_DELAY					100

#define		DLCORE_DELAY				10
#define		EXITDLCORE_DELAY			100

#endif //__OSG4WEB_IEOSG4WEB_DEFINES__