#ifndef __OSG4WEB_IEOSG4WEB_DEFINES__
#define __OSG4WEB_IEOSG4WEB_DEFINES__ 1


#define		OSG4WEB_SHELL_NAME						"ieOSG4Web"

#define		APPEND_TEMP_DIRECTORY					"\\osg4web"
#define		APPEND_CORES_DIRECTORY					"\\osg4web"


//Object Options Defines
#define		OBJECT_OPTION_ADVCORE			"ADVCore"
#define		OBJECT_OPTION_ADVCSTARTOPT		"ADVCoreStartOptions"
#define		OBJECT_OPTION_ADVCINITOPT		"ADVCoreInitOptions"
#define		OBJECT_OPTION_ADVCORESHA1		"ADVCoreSHA1"
#define		OBJECT_OPTION_ADVCOREDEP		"ADVCoreDep"
#define		OBJECT_OPTION_ADVCOREDEPSHA1	"ADVCoreDepSHA1"
#define		OBJECT_OPTION_LOADCOREOPT		"LoadCoreOptions"
#define		OBJECT_OPTION_ENABLELOGS		"EnableDiskLogs"


#endif //__OSG4WEB_IEOSG4WEB_DEFINES__