#ifndef __OSG4WEB_LOADEROPENGL_DEFINES__
#define	__OSG4WEB_LOADEROPENGL_DEFINES__ 1


#define		OSG4WEB_LOADEROPENGL_LIBNAME			"osg4web : Loader OpenGL"
#define		OSG4WEB_LOADEROPENGL_VERSION			"1.0.0.0"
#define		OSG4WEB_LOADEROPENGL_NAME				"LoaderOpenGL"

#define		OSG4WEB_COLORVEC_GREEN					0.21f, 0.48f, 0.03f
#define		OSG4WEB_COLORVEC_RED					1.0f, 0.12f, 0.06f
#define		OSG4WEB_COLORVEC_BLUE					0.20f, 0.45f, 0.60f

#define		OSG4WEB_COLORVEC_GRAY					0.85f, 0.85f, 0.85f

#define		OSG4WEB_COLORVEC_WHITE					1.0f, 1.0f, 1.0f

#define		OSG4WEB_BACKGROUND_COLOR 				OSG4WEB_COLORVEC_WHITE

#define		OSG4WEB_LOADEROPENGL_LOGO_NAME_PREFIX		"logo"
#define		OSG4WEB_LOADEROPENGL_TITLE_NAME_PREFIX		"title"
#define		OSG4WEB_LOADEROPENGL_MESSAGE_NAME_PREFIX	"message"

#define		OSG4WEB_LOADEROPENGL_NUM_LOGO_FRAMES	41
#define		OSG4WEB_LOADEROPENGL_NUM_TITLE_FRAMES	1
#define		OSG4WEB_LOADEROPENGL_NUM_MESSAGE_FRAMES	9

#define		OSG4WEB_LOADEROPENGL_IMAGES_EXTENSIONS	".jpg"
#define		OSG4WEB_LOADEROPENGL_IMAGES_SUBDIR		"img"


#endif //__OSG4WEB_LOADEROPENGL_DEFINES__
